from app.constants import WINDOW_WIDTH
import math

CALENDAR_CELL_WIDTH = 100
CALENDAR_CELL_HEIGHT = 100
EVENT_VIEW_MINROWSIZE = 15


SORT_MENU_WIDTH = WINDOW_WIDTH * 0.1

LISTVIEW_COLS = ["Date:", "Description:", "People:", "Location:", "Files:"]
LISTVIEW_HEADER_HEIGHT = 40
LISTVIEW_COL_WIDTH = (WINDOW_WIDTH - SORT_MENU_WIDTH) // len(LISTVIEW_COLS)
LISTVIEW_DATE_COL_WIDTH = int(math.floor(LISTVIEW_COL_WIDTH * 0.25) + 15)
LISTVIEW_DESCR_COL_WIDTH = LISTVIEW_DATE_COL_WIDTH * 3
LISTVIEW_LOCATION_COL_WIDTH = LISTVIEW_COL_WIDTH // 2
LISTVIEW_FILE_COL_WIDTH = LISTVIEW_COL_WIDTH
LISTVIEW_PEOPLE_COL_WIDTH = LISTVIEW_FILE_COL_WIDTH // 2
LISTVIEW_ROW_HEIGHT = LISTVIEW_COL_WIDTH // 2
LISTVIEW_ROW_WIDTH = LISTVIEW_DATE_COL_WIDTH + LISTVIEW_DESCR_COL_WIDTH + LISTVIEW_LOCATION_COL_WIDTH + \
                     LISTVIEW_FILE_COL_WIDTH + LISTVIEW_PEOPLE_COL_WIDTH
#LISTVIEW_HEADER_BG_COLOR = '#898997'
LISTVIEW_HEADER_BG_COLOR = '#3c3c42'
LISTVIEW_TABLE_BG_COLOR = '#53525c'
LISTVIEW_TABLE_FONT_COLOR = "#ffffff"
LISTVIEW_TABLE_BG_COLOR2 = '#3D3C42'
LISTVIEW_HEADER_BG_COLOR2 = '#302c2c'